# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lev7RjK8oNpim8tvVpx0HqfAYBRItnr7
"""

import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(0, 2 * np.pi, 1000)
y = np.sin(x)

plt.figure(figsize=(10, 5))
plt.plot(x, y, label="y = sin(x)", color="blue", linewidth=2)
plt.title("Sinusoidal Graph", fontsize=16)
plt.xlabel("x (radians)", fontsize=12)
plt.ylabel("y", fontsize=12)
plt.axhline(0, color='black', linewidth=0.5, linestyle='--')
plt.axvline(0, color='black', linewidth=0.5, linestyle='--')
plt.grid(alpha=0.5)
plt.legend(fontsize=12)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x = np.random.rand(50) * 10
y = np.random.rand(50) * 10
plt.scatter(x, y)
plt.show()